version: '3.1'

services:

  db:
    image: postgres:15.3-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  postgres-data: